In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)

2.1.0


In [3]:
model = tf.keras.Sequential([
    tf.keras.layers.BatchNormalization(name='bn', input_shape=(1,))
])

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bn (BatchNormalization)      (None, 1)                 4         
Total params: 4
Trainable params: 2
Non-trainable params: 2
_________________________________________________________________


In [5]:
print(model.layers[0].trainable)

True


In [6]:
for w in model.trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn/gamma:0                    [1.]
bn/beta:0                     [0.]


In [7]:
for w in model.non_trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn/moving_mean:0              [0.]
bn/moving_variance:0          [1.]


In [8]:
model.layers[0].trainable = False

In [9]:
print(model.layers[0].trainable_weights)

[]


In [10]:
for w in model.non_trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn/gamma:0                    [1.]
bn/beta:0                     [0.]
bn/moving_mean:0              [0.]
bn/moving_variance:0          [1.]


In [11]:
model = tf.keras.Sequential([
    tf.keras.layers.BatchNormalization(name='bn', input_shape=(1,))
])

In [12]:
for w in model.non_trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn_1/moving_mean:0            [0.]
bn_1/moving_variance:0        [1.]


In [13]:
a = np.array([[100]]).astype('float32')
print(a)

[[100.]]


In [14]:
print(a.shape)

(1, 1)


In [15]:
print(model(a, training=True))

tf.Tensor([[0.]], shape=(1, 1), dtype=float32)


In [16]:
for w in model.non_trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn_1/moving_mean:0            [1.]
bn_1/moving_variance:0        [0.99]


In [17]:
for i in range(1000):
    model(a, training=True)

In [18]:
for w in model.non_trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn_1/moving_mean:0            [99.99573]
bn_1/moving_variance:0        [4.273953e-05]


In [19]:
print(model(a, training=True))

tf.Tensor([[0.]], shape=(1, 1), dtype=float32)


In [20]:
print(model(a, training=False))

tf.Tensor([[0.13110352]], shape=(1, 1), dtype=float32)


In [21]:
print(model.predict(a))

[[0.13110352]]


In [22]:
model.layers[0].trainable = False

In [23]:
print(model(a, training=True))

tf.Tensor([[0.13110352]], shape=(1, 1), dtype=float32)


In [24]:
model = tf.keras.Sequential([
    tf.keras.layers.BatchNormalization(name='bn', input_shape=(1,))
])

In [25]:
for w in model.non_trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn_2/moving_mean:0            [0.]
bn_2/moving_variance:0        [1.]


In [26]:
for i in range(1000):
    model(a, training=False)

In [27]:
for w in model.non_trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn_2/moving_mean:0            [0.]
bn_2/moving_variance:0        [1.]


In [28]:
print(model(a, training=False))

tf.Tensor([[99.95004]], shape=(1, 1), dtype=float32)


In [29]:
print(model.predict(a))

[[99.95004]]


In [30]:
print((100 - 0) / np.sqrt(1 + 0.001))

99.95003746877732


In [31]:
model = tf.keras.Sequential([
    tf.keras.layers.BatchNormalization(name='bn', input_shape=(1,))
])

In [32]:
for w in model.non_trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn_3/moving_mean:0            [0.]
bn_3/moving_variance:0        [1.]


In [33]:
model.layers[0].trainable = False

In [34]:
for i in range(1000):
    model(a, training=True)

In [35]:
for w in model.non_trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn_3/gamma:0                  [1.]
bn_3/beta:0                   [0.]
bn_3/moving_mean:0            [0.]
bn_3/moving_variance:0        [1.]


In [36]:
print(model(a, training=True))

tf.Tensor([[99.95004]], shape=(1, 1), dtype=float32)


In [37]:
print(model(a, training=False))

tf.Tensor([[99.95004]], shape=(1, 1), dtype=float32)


In [38]:
print(model.predict(a))

[[99.95004]]


In [39]:
model.compile(optimizer='adam', loss='mean_squared_error')

In [40]:
model.fit(a, a, verbose=0)

In [41]:
for w in model.non_trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn_3/gamma:0                  [1.]
bn_3/beta:0                   [0.]
bn_3/moving_mean:0            [0.]
bn_3/moving_variance:0        [1.]


In [42]:
model.layers[0].trainable = True

In [43]:
model.compile(optimizer='adam', loss='mean_squared_error')

In [44]:
model.fit(a, a, verbose=0)

In [45]:
for w in model.trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn_3/gamma:0                  [1.]
bn_3/beta:0                   [0.001]


In [46]:
for w in model.non_trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn_3/moving_mean:0            [1.]
bn_3/moving_variance:0        [0.99]


In [47]:
model.fit(a, a, epochs=1000, verbose=0)

In [48]:
for w in model.trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn_3/gamma:0                  [1.]
bn_3/beta:0                   [0.9988577]


In [49]:
for w in model.non_trainable_weights:
    print('{:<30}{}'.format(w.name, w.numpy()))

bn_3/moving_mean:0            [99.99573]
bn_3/moving_variance:0        [4.273953e-05]
